// AUTO-GENERATED by tools/embed_payload.py — do not edit by hand.
// Run: python3 tools/embed_payload.py payload/build/payload.elf src/loader/payload_blob.cpp
#include <cstdint>
#include <cstddef>

// Stub: replace with generated output after building the payload.
extern const uint8_t  kPayload[]     = { 0x00 };
extern const size_t   kPayloadSize   = 1;
extern const uint64_t kEntryOffset   = 0;
extern const uint64_t kRelocOffsets[] = {};
extern const size_t   kRelocCount    = 0;
